### ISSUE TITLE
as.matrix() method for sub-kernels

### ISSUE THREAD

**Issue by Aariq** [padrinoDB/ipmr#63]
I would expect `as.matrix(ipm$sub_kernels$P)` to print a matrix, but it prints the same output as `ipm$sub_kernels$P`.  It might be nice to have an `as.matrix()` method that strips the `class()` back to just `"matrix" "array"`.

**Comment by levisc8** [comment]
This is now implemented on the [`report_ipm` branch](https://github.com/levisc8/ipmr/blob/report_ipm/R/generics.R#L2711). That one isn't as stable, but if you want to test it out, its up there now.
