### ISSUE TITLE
Specifying constants 

### ISSUE THREAD

**Issue by MaartenPostuma** [padrinoDB/ipmr#71]
From exercise 1 from the tutorial at evodemos:
When defining a kernel with a constant in it such as a seedproduction with a germination chance using the variable name from the data list gives a cryptic error if the name is the same in the data list as in the formula.
`Error in (function (...)  : 
  promise already under evaluation: recursive default argument reference or earlier problems?`
setting g_0 = 0.02465088, or g_0 as g_1 in the kernel does work correctly,
and so does not specifying g_0.

```
dat_list <- c(s_pars, g_pars, 
              repr_pars, seed_pars,
              f_d_pars,
              list(g_0 = 0.02465088,
                   g_1 = 0.01433191,
                   g_2 = 0.0005732764))

define_kernel(
    name= "F",
    family = "CC",
    formula = F_p*F_n*F_d*g_0*d_area,
    F_p = plogis(alpha_fp+beta_fp*area_1),
    F_n = plogis(alpha_fn+beta_fn*area_1),
    F_d = dnorm(area_2,fd_mu,fd_sd),
    g_0 = g_0,
    data_list=dat_list,
    states= list(c("area")),
    evict_cor = T,
    evict_fun= truncated_distributions("norm","F_d")
    )

```

**Comment by levisc8** [comment]
Hi Maarten, sorry for the slow response! Try removing the line: 

```
g_0 = g_0
```

That should solve the issue. I am not sure why that is included in the tutorial, but I'm fairly sure that is what is giving you the error.

**Comment by levisc8** [comment]
Closing this, but feel free to reopen if the issue occurs again.
